import {
  Activity,
  ArrowUpDown,
  BarChart,
  BarChart3,
  Calendar,
  ChartColumnIncreasing,
  CircleDot,
  Columns,
  Crosshair,
  Dumbbell,
  Eye,
  Flag,
  Footprints,
  Gauge,
  GitCompare,
  Goal,
  Hash,
  Heart,
  Layers,
  LayoutGrid,
  LineChart,
  ListChecks,
  Map,
  Maximize,
  Medal,
  MonitorPlay,
  Percent,
  PieChart,
  Pin,
  Radar,
  Shield,
  Star,
  Swords,
  Table,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Users,
  Waypoints,
  Zap,
  AlarmClock,
  Award,
  Bell,
  BookOpen,
  Briefcase,
  CalendarRange,
  CheckCircle2,
  CircleDollarSign,
  ClipboardList,
  Compass,
  Crown,
  Database,
  FileText,
  Flame,
  FolderKanban,
  HeartPulse,
  MapPinned,
  Megaphone,
  Scale,
  Search,
  ShieldCheck,
  Shirt,
  Tv,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/**
 * Mapping of icon keys (slug or category name) to Lucide icon components.
 * Used across all dashboard cards.
 */
export const dashboardIconMap = {
  Activity,
  AlarmClock,
  ArrowUpDown,
  Award,
  BarChart,
  BarChart3,
  Bell,
  BookOpen,
  Briefcase,
  Calendar,
  CalendarRange,
  ChartColumnIncreasing,
  CheckCircle2,
  CircleDollarSign,
  CircleDot,
  ClipboardList,
  Columns,
  Compass,
  Crosshair,
  Crown,
  Database,
  Dumbbell,
  Eye,
  FileText,
  Flag,
  Flame,
  FolderKanban,
  Footprints,
  Gauge,
  GitCompare,
  Goal,
  Hash,
  Heart,
  HeartPulse,
  Layers,
  LayoutGrid,
  LineChart,
  ListChecks,
  Map,
  MapPinned,
  Maximize,
  Medal,
  Megaphone,
  MonitorPlay,
  Percent,
  PieChart,
  Pin,
  Radar,
  Scale,
  Search,
  Shield,
  ShieldCheck,
  Shirt,
  Star,
  Swords,
  Table,
  Target,
  Timer,
  TrendingUp,
  Trophy,
  Tv,
  Users,
  Waypoints,
  Wrench,
  Zap,
} as const satisfies Record<string, LucideIcon>;

/**
 * Returns the Lucide icon component for a given icon key.
 * Falls back to `ChartColumnIncreasing` if the key is not found.
 */
export function getDashboardIcon(
  iconName: string | null | undefined
): LucideIcon {
  return (
    dashboardIconMap[iconName as keyof typeof dashboardIconMap] ??
    ChartColumnIncreasing
  );
}

/** All available icon keys for use in selectors / admin UIs. */
export const DASHBOARD_ICON_OPTIONS = Object.keys(dashboardIconMap) as Array<
  keyof typeof dashboardIconMap
>;
